### ISSUE TITLE
Bug related to angular-cli if using moment in your app

### ISSUE THREAD

**Issue by maxailloud** [superstarmcawesome/angular2-daterangepicker#1]
FYI there is currently a bug in angular-cli and webpack (or maybe just one of them) preventing to use your module if we use momentjs in our app at the same time. Look at it [here](https://github.com/angular/angular-cli/issues/2141).

I mean we can use it, but in my case I have the case because of some other datepicker used in my app (I have some shared code between my apps).

**Comment by superstarmcawesome** [comment]
hey there. I will check on the weekend. Which other datepicker you're using? I have also the ng2-bootstrap with its datepicker running. but I'm using the angular 2 seed by mgechev.. and there without any problems.

**Comment by maxailloud** [comment]
I'm using the datepicker from ng2-bootstrap too.
I'm using angular-cli generated project, it seems the issue is with webpack loading momentjs.

I have an issue with momentjs with one of my package that uses momentjs too.

**Comment by superstarmcawesome** [comment]
sounds that the problem is with cli and not ng2-bootstrap or the daterangepicker itself. cause i can easily import moment...

**Comment by maxailloud** [comment]
To use your directive I needed to add momentjs, jquery and bootstrap in the list of scripts in the angular-cli.json file.
By doing so I can't use momentjs in my app anymore using `import * as moment from 'moment;` because it is empty, need to use `declare var moment: any;`.
But that's not ideal, and yes it's an issue with angular-cli.
